// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2WKjcqOof_prEj4dyEhdIXY__eHdUUI',
    appId: '1:745060405583:web:a0295135a19a366276353a',
    messagingSenderId: '745060405583',
    projectId: 'madebyhands-77f87',
    authDomain: 'madebyhands-77f87.firebaseapp.com',
    storageBucket: 'madebyhands-77f87.firebasestorage.app',
    measurementId: 'G-BB61FBBC7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXLSd4e2cuf26PjLQ2KsUUsT6KHnt16g',
    appId: '1:745060405583:android:fb81dfd4e100c30576353a',
    messagingSenderId: '745060405583',
    projectId: 'madebyhands-77f87',
    storageBucket: 'madebyhands-77f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmC0Win1KQpnMYTRt9exEzaUH_D0FPpgc',
    appId: '1:745060405583:ios:cc59275367486c4f76353a',
    messagingSenderId: '745060405583',
    projectId: 'madebyhands-77f87',
    storageBucket: 'madebyhands-77f87.firebasestorage.app',
    iosBundleId: 'com.example.madebyhands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmC0Win1KQpnMYTRt9exEzaUH_D0FPpgc',
    appId: '1:745060405583:ios:cc59275367486c4f76353a',
    messagingSenderId: '745060405583',
    projectId: 'madebyhands-77f87',
    storageBucket: 'madebyhands-77f87.firebasestorage.app',
    iosBundleId: 'com.example.madebyhands',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2WKjcqOof_prEj4dyEhdIXY__eHdUUI',
    appId: '1:745060405583:web:b3e943d312d91c5f76353a',
    messagingSenderId: '745060405583',
    projectId: 'madebyhands-77f87',
    authDomain: 'madebyhands-77f87.firebaseapp.com',
    storageBucket: 'madebyhands-77f87.firebasestorage.app',
    measurementId: 'G-CGY852CTGS',
  );
}
